apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
    - name: kubia
      image: luksa/kubia  # 컨테이너 이미지
      ports:  # 애플리케이션이 수신하는 포트
      - containerPort: 8080
        protocol: TCP